name: Build Trading Bot APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Crée la variable de date pour GitHub
      - name: Generate Build Date for GitHub
        id: date
        run: echo "CURRENT_DATE=$(date +'%d%m%Y-%H'H'%M')" >> $GITHUB_ENV

      - name: Install & Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.1.1'
          cache-disabled: true

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          # Ici on écrit en dur le début "V1.0.1" pour correspondre au build.gradle
          # et on ajoute la date dynamique juste après
          name: Fonda_IOF_V1.0.1_${{ env.CURRENT_DATE }}
          path: app/build/outputs/apk/debug/**/*.apk
          retention-days: 30
